import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync } from "fs";
import { generateNotices } from "./scripts/generate-third-party-notices.mjs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Plugin to import markdown files as strings
const markdownPlugin = {
	name: 'markdown',
	setup(build) {
		build.onLoad({ filter: /\.md$/ }, async (args) => {
			const text = readFileSync(args.path, 'utf8');
			return {
				contents: `export default ${JSON.stringify(text)}`,
				loader: 'js',
			};
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	metafile: prod,
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [markdownPlugin],
});

if (prod) {
	const result = await context.rebuild();
	if (result.metafile) {
		const { writeFileSync } = await import("node:fs");
		writeFileSync("build-metadata.json", JSON.stringify(result.metafile));
		const notices = generateNotices(result.metafile);
		const legal = [readFileSync("LICENSE", "utf8"), readFileSync("NOTICE.md", "utf8"), notices].join("\n\n");
		const comment = legal.split("\n").map(line => "// " + line).join("\n") + "\n";
		writeFileSync("main.js", comment + readFileSync("main.js", "utf8"));
	}
	await context.dispose();
} else {
	await context.watch();
}
